### ISSUE TITLE
Shopify graphQL proxy

### ISSUE THREAD

**Issue by emcfarlane** [TheSecurityDev/simple-koa-shopify-auth#17]
Thanks so much for keeping the library going! Looks like it works but failing to get the graphqlProxy working with it.

```
  router.post(
    "/graphql",
    verifyRequest({ returnHeader: true }),
    async (ctx, next) => {
      await Shopify.Utils.graphqlProxy(ctx.req, ctx.res);
    }
  );
```
But get 404 with this method.

Have tried the latest version of https://www.npmjs.com/package/@shopify/koa-shopify-graphql-proxy
```
Error forwarding web request: Error: connect ECONNREFUSED ::1:53462
```
Any ideas?

**Comment by TheSecurityDev** [comment]
Firstly, if you are getting `graphqlProxy` from `Shopify.Utils.graphqlProxy`, then I don't think there's any reason to use `@shopify/koa-shopify-graphql-proxy`.

But I think the issue is you are not responding to the request.

You need to do something like:

```js
router.post("/graphql", verifyRequest({ returnHeader: true }), async (ctx) => {
   try {
      const response = await Shopify.Utils.graphqlProxy(ctx.req, ctx.res);
      ctx.response.status = 200;
      ctx.response.body = response.body;
   } catch (err) {
      ctx.response.status = 500;
      ctx.response.body = "GraphQL proxy error";
   }
});
```

There might be a way to get the status code from the response (instead of hardcoding 200), but I'm not exactly sure how, since Typescript isn't sure if `response.status` exists.

**Comment by emcfarlane** [comment]
Was working before adding changing the auth library to `simple-koa-shopify-auth`, but might be unrelated. Thanks for looking into it I'll update here or close soon.

**Comment by emcfarlane** [comment]
https://github.com/Shopify/shopify-api-js/blob/v5/src/utils/graphql_proxy.ts#L9

**Comment by emcfarlane** [comment]
https://github.com/Shopify/shopify-api-js/pull/324/files thanks didn't notice the breaking changes in the API!
